modLoader = "javafml"
loaderVersion = "38,)"
license = "GNU Lesser General Public License v3.0"

[[mods]]
modId = "blossom"
version = "${version}"
displayName = "Blossom"
displayURL = "https://github.com/yurisuika/Blossom"
issueTrackerURL = "https://github.com/yurisuika/Blossom/issues"
logoFile = "icon.png"
authors = "yurisuika"
description = '''
Fruit blossoms from trees!
'''

[[dependencies.blossom]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.19)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blossom]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "AFTER"
side = "BOTH"