modLoader = "javafml"
loaderVersion = "38,)"
license = "GNU Lesser General Public License v3.0"

[[mods]]
modId = "blossom"
version = "${version}"
displayName = "Blossom"
displayTest = "MATCH_VERSION"
displayURL = "https://github.com/yurisuika/Blossom"
issueTrackerURL = "https://github.com/yurisuika/Blossom/issues"
logoFile = "icon.png"
authors = "yurisuika"
description = '''
Apples blossom upon leaves by the pollen from bees!
'''

[[dependencies.blossom]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.19)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blossom]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"