modLoader="javafml"
loaderVersion="43,)"
license="GNU General Public License 3.0"
[[mods]]
modId="blossom"
version="${file.jarVersion}"
displayName="Blossom"
logoFile="blossom.png"
authors="yurisuika"
description='''
Fruit blossoms from trees!
'''
[[dependencies.raised]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="AFTER"
    side="CLIENT"
