modLoader = "javafml"
loaderVersion = "1,)"
license = "GNU Lesser General Public License v3.0"

[[mods]]
modId = "blossom"
version = "${version}"
displayName = "Blossom"
displayTest = "MATCH_VERSION"
displayURL = "https://github.com/yurisuika/Blossom"
issueTrackerURL = "https://github.com/yurisuika/Blossom/issues"
logoFile = "icon.png"
authors = "yurisuika"
description = '''
Apples blossom upon leaves by the pollen from bees!
'''

[[mixins]]
config = "blossom.mixins.json"

[[dependencies.blossom]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blossom]]
modId = "neoforge"
type = "required"
versionRange = "[21.4,)"
ordering = "NONE"
side = "BOTH"